name: Demo

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  determine-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.env.outputs.environment }}
      should-deploy: ${{ steps.env.outputs.should-deploy }}
    steps:
      - name: Set environment
        id: env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "should-deploy=true" >> $$GITHUB_OUTPUT
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "should-deploy=true" >> $$GITHUB_OUTPUT
          fi
  build-docker:
    runs-on: ubuntu-latest
    needs: determine-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        run: |
          echo "building docker for ${{ needs.determine-environment.outputs.environment }}"
  test:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        run: |
          echo "testing for ${{ needs.determine-environment.outputs.environment }}"
  push-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        run: |
          echo "push docker to registry for ${{ needs.determine-environment.outputs.environment }}"
  deploy:
    runs-on: ubuntu-latest
    needs: push-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        run: |
          echo "deploying to ${{ needs.determine-environment.outputs.environment }}"